from django.db import models

# Create your models here.

class Entry(models.Model):
    accelX = models.IntegerField()
    accelY = models.IntegerField()
    accelZ = models.IntegerField()
    activity = models.CharField(max_length=64)
    batteryLevel = models.FloatField()
    beaconHumidity = models.FloatField()
    beaconLightLevel = models.FloatField()
    beaconName = models.CharField(max_length=64)
    beaconNoiseLevel = models.FloatField()
    beaconTemperature = models.FloatField()
    coreBodyTemp = models.FloatField()
    coreBodyTemperatureConfidence = models.FloatField()
    coreBodyTemperatureTrend = models.CharField(max_length=64)
    dailyActiveKCalsExpended = models.FloatField()
    dailyKCalsExpended = models.FloatField()
    dailyStepsRun = models.IntegerField()
    dailyStepsWalk = models.IntegerField()
    excessiveMotion = models.BooleanField()
    fallDetectFreefallPeriod = models.IntegerField()
    fallDetectMaxmG = models.IntegerField()
    fallDetectNoMotionPeriod = models.IntegerField()
    fallDetectReportId = models.IntegerField()
    greenCounter = models.IntegerField()
    greenCounter2 = models.IntegerField()
    healthState = models.CharField(max_length=64)
    heartRate = models.FloatField()
    heartRateConfidence = models.IntegerField()
    heartRateTrend = models.CharField(max_length=64)
    heartRateVariability = models.FloatField()
    heartRateVariabilityMotion = models.BooleanField()
    irCounter = models.IntegerField()
    isExtendedReport = models.BooleanField()
    loggingActive = models.BooleanField()
    lowPI = models.BooleanField()
    lowSignalQuality = models.BooleanField()
    perfusionIndexInfrared = models.FloatField()
    perfusionIndexRed = models.FloatField()
    readingQuality = models.CharField(max_length=64)
    readingTime = models.IntegerField()
    redCounter = models.IntegerField()
    respirationRate = models.FloatField()
    respirationRateConfidence = models.IntegerField()
    respirationRateTrend = models.CharField(max_length=64)
    restingCoreBodyTemperature = models.FloatField()
    restingHeartRate = models.FloatField()
    restingRespirationRate = models.FloatField()
    restingSpO2 = models.FloatField()
    rrInterval = models.FloatField()
    rrIntervalConfidence = models.IntegerField()
    skinContact = models.CharField(max_length=64)
    skinTemp = models.FloatField()
    sleepQuality = models.CharField(max_length=64)
    spO2 = models.FloatField()
    spO2Confidence = models.IntegerField()
    spO2RValue = models.FloatField()
    spO2Trend = models.CharField(max_length=64)
    stressLevel = models.IntegerField()
    time = models.IntegerField()
    unreliableR = models.BooleanField()
    userMotion = models.CharField(max_length=64)
    userPosition = models.CharField(max_length=64)
    macAddress = models.CharField(max_length=64)

